version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  segments:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: ${POSTGRES_NAME}
      HTTP_SERVER_ADDR: ${HTTP_SERVER_ADDR}
      GIN_MODE: ${GIN_MODE}
      SERVICE_NAME: ${SERVICE_NAME}
    ports:
      - ${HTTP_SERVER_ADDR}

